apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-asterisk-secret
type: Opaque
stringData:
  pjsip: |
    [transport-udp]
    type = transport
    protocol = udp
    bind = 0.0.0.0:{{ .Values.asterisk.sip.udp_port }}

    [transport-tcp]
    type = transport
    protocol = tcp
    bind = 0.0.0.0:{{ .Values.asterisk.sip.tcp_port }}
    
    [{{ .Values.asterisk.endpoint.name }}]
    type=endpoint
    transport=transport-tcp
    context=echo
    disallow=all
    allow=ulaw
    auth=auth-{{ .Values.asterisk.endpoint.name }}
    aors=aors-{{ .Values.asterisk.endpoint.name }}

    [auth-{{ .Values.asterisk.endpoint.name }}]
    type=auth
    auth_type=userpass
    password={{ .Values.asterisk.endpoint.password }}
    username={{ .Values.asterisk.endpoint.username }}

    [aors-{{ .Values.asterisk.endpoint.name }}]
    type=aor
    max_contacts=3
  http: |
    [general]
    servername=Asterisk
    enabled=yes
    bindaddr=0.0.0.0
    bindport={{ .Values.asterisk.http.port }}
    sessionlimit=10
