replicaCount: 1
appComponent: asterisk
nodeSelector: {}

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

asterisk:
  resources:
    enabled: true
    limits:
      cpu: "400m"
      memory: "200Mi"
    requests:
      cpu: "100m"
      memory: "50Mi"
  image: evgrdan/asterisk
  tag: 20.9-alpine
  sip:
    tcp_port: 5060
    udp_port: 5060
  http:
    port: 8088
  endpoint:
    name: 101
    password: password
    username: user

metrics:
  enabled: true
  port: 8089
  prometheusRule:
    enabled: true
    namespace: "monitoring"
    rules:
      - alert: Endpoint is down
        expr: max(asterisk_endpoints_state) by (resource) == 1
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: Endpoint {{ "{{ $labels.resource }}" }} is offline
